Postinst reliability improvements

diff --git a/sources/endor/postinst b/sources/endor/postinst
--- a/sources/endor/postinst
+++ b/sources/endor/postinst
@@ -1,11 +1,16 @@
 #!/bin/sh
 
+echo ""
+echo "ENDOR POSTINST"
+echo "==================="
+
+
 cd /opt/lib/endor
 tar -xzf long-filepaths.tar.gz
 
-#
 # This block sets up the machine as a real machine,
-# that speaks to a physical embedded.
+# that speaks to a physical embedded (i.e. not a 
+# virtual machine)
 #
 if [ -e /opt/bin/calnex.endor.instrument.controller ]; then
     rm /opt/bin/calnex.endor.instrument.controller
@@ -13,66 +18,55 @@ fi
 
 ln -s  /opt/bin/calnex.endor.instrument.controller.physicalinstrument /opt/bin/calnex.endor.instrument.controller 
 
+
+# Stop the database server and wait for that to complete (it's not likely
+# to be running, but this is belt-and-braces stuff)
 /opt/etc/init.d/S95postgresql stop
 sleep 3
 
+# Now call postgres' postinst code to get the server configured, then
+# start the database server running
+#
 /opt/lib/ipkg/info/postgresql.postinst
-
-echo "********************"
-echo "ENDOR POSTINST: Returned from postgres postinst"
-echo ""
-ps aux | grep -i post
-
-echo ""
-
-echo "Listing the database startup script:"
-ls -l /opt/etc/init.d/S95postgresql
-
 /opt/etc/init.d/S95postgresql start
+
+# This loop waits for the database server to be available
+#
 echo "waiting for DB daemon to start"
 
-
 pgdata=/opt/var/pgsql/data
+wait_count=20
+
 pg_ctl status -D $pgdata
-pg_running=3
-while [ $pg_running != 0 ]
+pg_running=$?
+
+while [ ${pg_running} -ne 0 ] && [ ${wait_count} -ne 0 ]
 do
-    echo "Not running yet, sleeping..."
+    echo "Database not running, waiting..."
     sleep 0.5
     pg_ctl status -D $pgdata
     pg_running=$?
+    wait_count=$(expr $wait_count - 1)
 done
 
-echo "Database reports itself running"
-
-
-# Debugging code added here.
-# 
+# Exit if we have failed
 #
+if [ $wait_count -eq 0 ]; then
+    echo "Failed to start database in Endor Postinst"
+    exit 1
+fi
 
-echo ""
-echo "We asked the database daemon to start three seconds ago"
-echo ""
-ps aux | grep -i post
-
-echo "Let's try to connect to it"
-echo "First using localhost"
-psql -h localhost -U calnex -d postgres -c "\dt"
-
-echo "**************************"
-echo "Let's try to connect to it"
-echo "Now using 127.0.0.1"
-psql -h 127.0.0.1 -U calnex -d postgres -c "\dt"
-
-echo "Finally a list of processes"
-ps aux
-
+# Note that we have succeeded
 #
-#
-# End of debugging code
+echo "Database running"
 
-
+# Rebuild the database, exit if the script reports failure
 python3 /opt/lib/endor/schema/Baseline/RebuildDb.py --superuser calnex --path /opt/lib/endor/schema/Baseline
+
+database_build_status=$?
+if [ $database_build_status -ne 0 ]; then
+    exit $database_build_status
+fi
 
 # And if any saved data exists, put that into the database too
 #
@@ -84,8 +78,7 @@ if [ -e /opt/lib/endor/utility/restore_persistent_data.py ]; then
     fi
 fi
 
+# Stop the database and finish
+#
 /opt/etc/init.d/S95postgresql stop
-# /opt/etc/init.d/S96endor-virtualinstrument start
-# /opt/etc/init.d/S97endor-instrumentcontroller start
-# /opt/etc/init.d/S98cat-remotingserver start
-# /opt/etc/init.d/S99endor-webapp start
+exit 0
diff --git a/sources/postgresql/postinst b/sources/postgresql/postinst
--- a/sources/postgresql/postinst
+++ b/sources/postgresql/postinst
@@ -11,22 +11,6 @@ pgdumpground="$pgver/dump"
 echo ""
 echo "POSTGRESQL POSTINST"
 echo "==================="
-echo "pghome:       ${pghome}"
-echo ""
-ls -l ${pghome}
-
-echo "pgdata:       ${pgdata}"
-ls -l ${pgdata}
-
-echo "pgver:        ${pgver}"
-ls -l ${pgver}
-
-echo "pgdumpground: ${pgdumpground}"
-ls -l ${pgdumpground}
-
-
-echo "Process Dump"
-ps aux
 
 if [ ! -d $pghome ]
 then
@@ -38,6 +22,7 @@ then
 fi
 
 # initdb if not done before
+#
 dbinited=0
 if [ -d $pgdata ]; then
     echo The $pgdata directory already exists
@@ -49,17 +34,10 @@ else
     dbinited=1
 fi
 
-# compatibility check and start db
-echo "Listing /opt/etc/init.d/S95postgresql start"
-cat /opt/etc/init.d/S95postgresql
-
-
-echo "Calling database start"
-
-#/opt/etc/init.d/S95postgresql start
+# Start the database server
+#
+echo "Starting database server"
 /opt/bin/postmaster -D /opt/var/pgsql/data &
-
-echo "Returned from call" 
 
 
 if [ "$dbinited." = "1." -a -n "`pidof postmaster`" ]; then
@@ -70,53 +48,56 @@ if [ "$dbinited." = "1." -a -n "`pidof postmaster`" ]; then
     echo "To allow access from network, see http://developer.postgresql.org/docs/postgres/runtime-config.html#RUNTIME-CONFIG-CONNECTION"
 fi
 
-echo "Now doing postgress running loop"
-echo "pgdata contains:"
-ls -l $pgdata
+# Waiting for database server to be available
 
-echo "ls of root"
-ls -l /
+wait_count=20
 
-echo "ls of the tmp folder"
-ls -l /tmp
+pg_ctl status -D $pgdata
+pg_running=$?
 
-pg_running=3
-count=25
-while [ $pg_running != 0 ]
+while [ ${pg_running} -ne 0 ] && [ ${wait_count} -ne 0 ]
 do
+    echo "Database not running, waiting..."
     sleep 0.5
     pg_ctl status -D $pgdata
     pg_running=$?
+    wait_count=$(expr $wait_count - 1)
 done
+
+# Exit if we have failed
+#
+if [ $wait_count -eq 0 ]; then
+    echo "Failed to start database in Postgres Postinst"
+    exit 1
+fi
 
 # Now loop waiting to see if we can connect via psql
 #
 psql_status=3
 count=20
+echo "Waiting for database server to accept connections"
 while [ ${psql_status} -ne 0 ] && [ ${count} -ne 0 ]
 do
+    echo "${count} iterations left"
     echo "Checking database connection status... localhost"
-    psql -h localhost -U calnex -d postgres -c "SELECT * FROM pg_catalog.pg_tables;"
-    psql_status = $?
+    psql -h localhost -U calnex -d postgres -c "SELECT * FROM pg_catalog.pg_tables;" > /dev/null
+    psql_status=$?
     echo "    psql status ${psql_status}"
-
-    echo "Checking database connection status... 127.0.0.1"
-    psql -h 127.0.0.1 -U calnex -d postgres -c "SELECT * FROM pg_catalog.pg_tables;"
-    psql_status = $?
-    echo "    psql status ${psql_status}"
-
-    ps aux
-    echo ""
-    echo ""
     sleep 0.5
+
     count=$(expr $count - 1)
-    echo ${count}
 done
 
+echo "Database now accepting connections"
+
+# Tidy up the database state
+#
 psql -h localhost -U calnex -d postgres -c "UPDATE pg_database SET datistemplate = FALSE WHERE datname = 'template1';"
 psql -h localhost -U calnex -d postgres -c "DROP DATABASE template1;"
 psql -h localhost -U calnex -d postgres -c "CREATE DATABASE template1 WITH TEMPLATE = template0 ENCODING = 'UNICODE';"
 psql -h localhost -U calnex -d postgres -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template1';"
 psql -h localhost -U calnex -d template1 -c "VACUUM FREEZE;"
 
+# And stop the server
+#
 /opt/etc/init.d/S95postgresql stop
